name: Repo Oush Pipeline
run-name: ${{ github.actor }} started the Push Pipeline

on:
  push

jobs:
  # Job 1
  run-test-runner:
    # Runner instance OS
    runs-on: ubuntu-latest
    # Deploy container on top of runner instance
    steps:
      - name: Make top-level project directory
        run: mkdir stocks-project
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: ./stocks-project
      # - name: Set checked out repo as a safe git directory
      #   run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - name: Install dependencies
        run: |
          cd stocks-project
          pip3 install -r requirements_dev.txt
      - name: Run Test Runner
        run: |
          cd stocks-project
          python3 tests/test_runner.py
      # - name: Build and run lorenz_96
      #   uses: ./.github/actions/build_run_model 
      #   with: 
      #     model: lorenz_96
      #     run-program: ./filter
      #     use-mpi: true
      #     mpi-n-tasks: 2
